name: Push on Master jobs

on:
  push:
    branches: [ '1.3' ]
  workflow_dispatch:

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
       
      # Mod Browser integration
      - uses: JavidPack/tModLoaderPublishIntegration@v0.11.8.4
        with:
          STEAMID64: ${{secrets.STEAMID64}}
          MODBROWSERPASSPHRASE: ${{secrets.MODBROWSERPASSPHRASE}}
          MODNAME: HEROsMod
     
      # Upload artifact for all builds
      - uses: actions/upload-artifact@v2
        with:
          name: .tmod file
          path: ~/tModLoader/ModLoader/Mods/HEROsMod.tmod
